language: php
php:
  - 5.5.9
before_script:
  - travis_retry composer self-update
install:
  - ./build.sh dev --no-frontend
script:
  - phpunit --coverage-clover=coverage.xml
  - vendor/bin/php-cs-fixer fix --dry-run
after_success:
  - bash <(curl -s https://codecov.io/bash)
