#!/bin/bash

PHP=`which php`
COMPOSER=`which composer`
NPM=`which npm`
PHPUNIT='vendor/bin/phpunit'

if [[ "dev" == "$1" ]]; then
    export SYMFONY_ENV=dev
else
    export SYMFONY_ENV=prod
fi

ERROR="\033[41m" # background red
GREEN="\033[42m" # background green
INFO="\033[43m" # yellow text
BACKGROUND="\033[44m" # background blue
BLACKTEXT="\033[30m"
COLOR="\033[39m" # text white
NC="\033[0m" # reset

function labelText {
    echo -e "\n${BACKGROUND}${COLOR} ${1} ${NC}\n"
}

function errorText {
    echo -e "\n${ERROR}${COLOR} ${1} ${NC}\n"
}

function infoText {
    echo -e "\n${INFO}${BLACKTEXT} ${1} ${NC}\n"
}

function successText {
    echo -e "\n${GREEN}${BLACKTEXT} ${1} ${NC}\n"
}

function writeErrorMessage {
    if [[ $? != 0 ]]; then
        errorText "${1}"
        exit 1
    fi
}

if [[ "dev" == "$1" ]]; then
    labelText "Development run"
    $COMPOSER install

    labelText "Copy dev index file"
    cp ./app/web/app_dev.php ./web/index.php

    labelText "Copy dev .htaccess file"
    cp ./app/web/.htaccess.dev ./web/.htaccess
else
    labelText "PRODUCTION optimize autoloader"
    $COMPOSER install --no-dev -o -a

    labelText "Copy prod index file"
    cp ./app/web/app_prod.php ./web/index.php

    labelText "Copy prod .htaccess file"
    cp ./app/web/.htaccess.prod ./web/.htaccess
fi

echo " " >> ./web/index.php
echo "// DO NOT EDIT THIS FILE. WILL BE REWRITTEN AT EVERY RELEASE !!!\n" >> ./web/index.php

labelText "Remove cache files"
find var/cache/* -maxdepth 0 -type d | xargs rm -rf

if [[ ! `echo "$@" | grep '\-\-no\-frontend'` ]]; then
    labelText "Run assets:install"
    $PHP $PWD/bin/console assets:install

    labelText "Run npm install"
    $NPM install
fi

if [[ "dev" == "$1" ]]; then
    $PHPUNIT
else
    infoText "Not development, no tests run"
fi

successText "Setup finished"

exit 0
