api_homepage:
    path:     /
    defaults: { _controller: ApiBundle:Default:index }

api_json_convert:
    path: /convert/json
    defaults: { _controller: ApiBundle:Convert:json }

api_base64_convert:
    path: /convert/base64
    defaults: { _controller: ApiBundle:Convert:base64 }

api_serialized_convert:
    path: /convert/serialized
    defaults: { _controller: ApiBundle:Convert:serialized }

api_responsive:
    path: /responsive
    defaults: { _controller: ApiBundle:Responsive:index }
