api_homepage:
    path:     /
    defaults: { _controller: ApiBundle:Default:index }

api_json2php:
    path: /json/{to}
    defaults: { _controller: ApiBundle:Json:index }
    requirements:
        to: "php|xml|serialize"

api_base64:
    path: /base64/{to}
    defaults: { _controller: ApiBundle:Base64:index }
    requirements:
        to: "encode|decode"

api_serialized:
    path: /serialized/{to}
    defaults: { _controller: ApiBundle:Serialized:index }
    requirements:
        to: "php|xml|json"
