services:
  api.twig_extension:
    class: ApiBundle\Twig\ApiTwigExtensions
    public: false
    tags:
      - { name: twig.extension }

  factory.transformer:
    class: ApiBundle\Transformer\FactoryTransformer
    arguments: ["@service_container"]
