services:
  api.twig_extension:
    class: ApiBundle\Twig\ApiTwigExtensions
    public: false
    tags:
      - { name: twig.extension }

  api.transfer_factory:
    public: true
    class: ApiBundle\Transfer\TransferFactory

  api.factory:
    public: true
    class: ApiBundle\Services\Factory
