services:
  api.twig_extension:
    class: ApiBundle\Twig\ApiTwigExtensions
    public: false
    tags:
      - { name: twig.extension }
#    api.example:
#        class: ApiBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
