services:
  api.twig_extension:
    class: ApiBundle\Twig\ApiTwigExtensions
    public: false
    tags:
      - { name: twig.extension }
  api.transfer_factory:
    class: ApiBundle\Transfer\TransferFactory
